services:
  db-admin:
    image: dbeaver/cloudbeaver
    container_name: db-admin
    restart: always
    ports:
      - "${BIND_IP:-127.0.0.1}:${DBVIEWER_PORT}:8978"
    mem_limit: 1000m
    mem_reservation: 500m
    memswap_limit: 2000m
    cpus: 1.0
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    networks:
      - general-net

volumes:
  cloudbeaver-data:

networks:
  general-net:
    name: general-net
    driver: bridge