services:
  redis:
    image: redis:latest
    container_name: redis-service  # Nama untuk container Redis
    restart: always
    ports:
      - "6379:6379"
    mem_limit: ${LIMIT_RAM}g
    cpus: ${LIMIT_CPU}
