services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-service # Menetapkan nama container untuk phpmyadmin
    restart: always
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./themes/blueberry:/var/www/html/themes/blueberry
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    mem_limit: ${LIMIT_RAM}g
    cpus: ${LIMIT_CPU}

volumes:
  mysql_data:
