services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: PGAdmin-Service
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${BIND_IP:-127.0.0.1}:${PGADMIN_PORT}:80"
    networks:
      - general-net

networks:
  general-net:
    name: general-net
    driver: bridge