services:
  minio:
    image: "${MINIO_IMAGE}"
    restart: unless-stopped
    container_name: minio
    ports:
      - "${MINIO_BIND_IP:-127.0.0.1}:${MINIO_PORT}:9000"
      - "${MINIO_BIND_IP:-127.0.0.1}:${MINIO_UI_PORT}:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_ROOT_USER_FILE: ""
      MINIO_ROOT_PASSWORD_FILE: ""
      MINIO_SERVER_URL: "${MINIO_SERVER_URL}"
      MINIO_BROWSER_REDIRECT_URL: "${MINIO_BROWSER_REDIRECT_URL}"
    volumes:
      - "${MINIO_VOLUME}:/data"
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      resources:
        limits:
          memory: "${MINIO_RAM}"
          cpus: "${MINIO_CPU}"
