services:
  actions-runner:
    image: ghcr.io/actions/actions-runner:latest
    container_name: actions-runner
    restart: unless-stopped
    entrypoint: ["/home/runner/run.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - github_runner_home:/home/runner
    tmpfs:
      - /tmp
    group_add:
      - "0"
    networks:
      - general-net
    user: "${RUNNER_UID:-1001}:${RUNNER_GID:-1001}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  github_runner_home:

networks:
  general-net:
    name: general-net
    driver: bridge
