services:
  # 1. Engine Ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${BIND_IP:-127.0.0.1}:11434:11434"
    environment:
      - OLLAMA_MAX_LOADED_MODELS=2 # Mengizinkan 2 model stanby bersamaan di RAM
      - OLLAMA_NUM_PARALLEL=2      # Mengizinkan 2 request diproses secara simultan
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - general-net

  # 2. Open-WebUI
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "${BIND_IP:-127.0.0.1}:3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - general-net

volumes:
  ollama_data:
  open-webui_data:

networks:
  general-net:
    name: general-net
    driver: bridge