services:
  actions-runner:
    image: ghcr.io/actions/actions-runner:latest
    container_name: actions-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - github_runner_config:/runner/_work
    networks:
      - general-net
    user: "${RUNNER_UID:-1001}:${RUNNER_GID:-1001}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  github_runner_config:

networks:
  general-net:
    name: general-net
    driver: bridge
